[package]
name = "tabler-icons"
version = "0.0.0"
entrypoint = "src/lib.typ"
authors = ["MaxMixAlex <MaxMixAlex@protonmail.com>"]
license = "MIT"
description = "Tabler Icons for Typst using webfont."
repository = "https://github.com/zyf722/typst-tabler-icons"
keywords = ["icon", "tabler"]
categories = ["text"]
exclude = ["/gallery/*"]
