name: Build (Manual)

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: Version bump type for the typst package
        type: choice
        options:
          - minor
          - major
          - patch
          - none
        default: minor
        required: true

env:
  FORCE_COLOR: 3
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - id: version
        name: Determine tabler-icons version
        run: |
          LATEST_TABLER_VERSION=$(npx semver $(gh release view -R tabler/tabler-icons --json tagName -q .tagName))
          PACKAGE_TABLER_VERSION=$(jq -r '.typst."tabler-version"' package.json)

          if [[ -z "$PACKAGE_TABLER_VERSION" || $(npx semver $PACKAGE_TABLER_VERSION -r "<$LATEST_TABLER_VERSION") ]]; then
            npx chalk -t "{yellow Tabler-icons has a new version: {bold $LATEST_TABLER_VERSION}.}"
            TABLER_VERSION=$LATEST_TABLER_VERSION
            jq --arg version "$TABLER_VERSION" '.typst."tabler-version" = $version' package.json > package.json.tmp \
            && mv package.json.tmp package.json
            echo "TABLER_UPDATED=true" >> $GITHUB_OUTPUT
          else
            npx chalk -t "{green Tabler-icons is up to date. Rebuilding with current version.}"
            TABLER_VERSION=$PACKAGE_TABLER_VERSION
            echo "TABLER_UPDATED=false" >> $GITHUB_OUTPUT
          fi
          echo "TABLER_VERSION=$TABLER_VERSION" >> $GITHUB_OUTPUT

      - name: Fetch tabler-icons
        env:
          TABLER_VERSION: ${{ steps.version.outputs.TABLER_VERSION }}
        run: |
          mkdir -p temp
          curl -L "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@$TABLER_VERSION/dist/tabler-icons.html" -o "temp/tabler-icons.html"
          curl -L "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@$TABLER_VERSION/dist/tabler-icons-filled.html" -o "temp/tabler-icons-filled.html"
          curl -L "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@$TABLER_VERSION/dist/fonts/tabler-icons.ttf" -o "temp/tabler-icons.ttf"
          curl -L "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@$TABLER_VERSION/dist/fonts/tabler-icons-filled.ttf" -o "temp/tabler-icons-filled.ttf"
          npx chalk -t "{green Downloaded tabler-icons files from jsdelivr.}"

      - name: Generate icons
        run: |
          npm run generate -- temp/tabler-icons.html temp/tabler-icons-filled.html src/lib-gen.typ gallery/gallery.typ
          npx chalk -t "{green Generated {bold.yellow src/lib-gen.typ} and {bold.yellow gallery/gallery.typ}.}"

      - name: Install typst
        run: |
          gh release download -R typst/typst -p 'typst-x86_64-unknown-linux-musl.tar.xz' -D temp
          npx chalk -t "{green Downloaded latest release of typst.}"
          tar -xvf temp/typst-x86_64-unknown-linux-musl.tar.xz -C /usr/local/bin --strip-components 1 typst-x86_64-unknown-linux-musl/typst
          npx chalk -t "{green Installed typst.}"
          typst -V

      - name: Generate gallery pdf
        run: |
          typst compile --root . --font-path temp gallery/gallery.typ gallery/gallery.pdf
          npx chalk -t "{green Compiled {bold.yellow gallery/gallery.pdf}.}"

      - name: Bump typst package version
        if: ${{ inputs.version_bump != 'none' }}
        env:
          VERSION_BUMP: ${{ inputs.version_bump }}
        run: |
          TYPST_PACKAGE_VERSION=$(awk -F'"' '/version =/ {print $2}' typst.toml)
          BUMPED_TYPST_PACKAGE_VERSION=$(npx semver $TYPST_PACKAGE_VERSION -i $VERSION_BUMP)
          sed -i "s/version = \"$TYPST_PACKAGE_VERSION\"/version = \"$BUMPED_TYPST_PACKAGE_VERSION\"/" typst.toml
          sed -i "s/#import \"@preview\/use-tabler-icons:$TYPST_PACKAGE_VERSION\": \*/#import \"@preview\/use-tabler-icons:$BUMPED_TYPST_PACKAGE_VERSION\": \*/" README.md
          echo "BUMPED_TYPST_PACKAGE_VERSION=$BUMPED_TYPST_PACKAGE_VERSION" >> $GITHUB_ENV
          npx chalk -t "{green Bumped typst package version in {bold.yellow typst.toml, README.md} to {bold.yellow $BUMPED_TYPST_PACKAGE_VERSION}.}"

      - id: commit
        name: Commit changes in a new branch
        env:
          TABLER_VERSION: ${{ steps.version.outputs.TABLER_VERSION }}
          TABLER_UPDATED: ${{ steps.version.outputs.TABLER_UPDATED }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          if [[ "$TABLER_UPDATED" == "true" ]]; then
            BRANCH="tabler-icons-$TABLER_VERSION"
            COMMIT_MSG="chore: update tabler-icons to $TABLER_VERSION"
          else
            BRANCH="rebuild-tabler-icons-$TABLER_VERSION"
            COMMIT_MSG="chore: rebuild with tabler-icons $TABLER_VERSION"
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          if [[ -z $(git branch --list $BRANCH) ]]; then
            npx chalk -t "{green Creating a new branch {bold.yellow $BRANCH}.}"
            git checkout -b $BRANCH
          else
            npx chalk -t "{green Switching to existing branch {bold.yellow $BRANCH}.}"
            git checkout $BRANCH
            git pull origin $BRANCH
          fi
          git add .

          if [[ -z $(git status --porcelain) ]]; then
            npx chalk -t "{yellow No changes to commit.}"
            echo "SKIP=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          git commit -m "$COMMIT_MSG"
          git push origin $BRANCH
          npx chalk -t "{green Pushed changes to {bold.yellow $BRANCH}.}"

      - name: Create PR
        if: ${{ steps.commit.outputs.SKIP != 'true' }}
        env:
          TABLER_VERSION: ${{ steps.version.outputs.TABLER_VERSION }}
          TABLER_UPDATED: ${{ steps.version.outputs.TABLER_UPDATED }}
        run: |
          if [[ "$TABLER_UPDATED" == "true" ]]; then
            ORIGINAL_RELEASE_MESSAGE=$(
              gh release view -R tabler/tabler-icons --json body -q .body
            )
            PR_TITLE="Update \`tabler-icons\` to $TABLER_VERSION"
            PR_BODY="This PR updates \`tabler-icons\` to version [v$TABLER_VERSION](https://github.com/tabler/tabler-icons/releases/tag/v$TABLER_VERSION).\n---\n$ORIGINAL_RELEASE_MESSAGE"
          else
            PR_TITLE="Rebuild with \`tabler-icons\` $TABLER_VERSION"
            PR_BODY="This PR rebuilds the package using \`tabler-icons\` $TABLER_VERSION (no upstream version change)."
          fi

          echo -e "$PR_BODY" | \
          gh pr create \
            --title "$PR_TITLE" \
            --base ${{ github.ref }} \
            --head $BRANCH \
            --label "manual-build" \
            --body-file -

          npx chalk -t "{green Created PR.}"
