name: Publish

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  FORCE_COLOR: 3
  GH_TOKEN: ${{ secrets.TOKEN }}
  TYPST_PACKAGE_INDEX_REPO_OWNER: zyf722
  TYPST_PACKAGE_INDEX_REPO_NAME: typst-packages
  COMMITTER_NAME: zyf722
  COMMITTER_EMAIL: MaxMixAlex@protonmail.com

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout library code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Sync package index
        run: |
          npx chalk -t "{yellow Syncing package index...}"
          gh repo sync $TYPST_PACKAGE_INDEX_REPO_OWNER/$TYPST_PACKAGE_INDEX_REPO_NAME

      - name: Checkout package index code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TYPST_PACKAGE_INDEX_REPO_OWNER }}/${{ env.TYPST_PACKAGE_INDEX_REPO_NAME }}
          token: ${{ secrets.TOKEN }}
          path: "./index"

      - name: Create package
        run: |
          NAME=$(sed -n 's/name = "\(.*\)"/\1/p' typst.toml)
          VERSION=$(sed -n 's/version = "\(.*\)"/\1/p' typst.toml)
          TARGET_DIR=$GITHUB_WORKSPACE/index/packages/preview/$NAME/$VERSION
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          mkdir -p $TARGET_DIR
          npx chalk -t "{green Created package folder {bold $NAME} {bold $VERSION}.}"

          readarray -t FILES < <(jq -r '.typst."dist-manifest"[]' package.json)
          for FILE in "${FILES[@]}"; do
            cp --parents $FILE $TARGET_DIR
          done

          npx chalk -t "{green Copied ${#FILES[@]} files to package folder.}"
      
      - name: Commit package
        run: |
          git config --global user.email $COMMITTER_EMAIL
          git config --global user.name $COMMITTER_NAME

          cd index

          git fetch origin
          if [[ $(git ls-remote --heads origin $NAME-$VERSION) ]]; then
            git checkout $NAME-$VERSION
            npx chalk -t "{yellow Branch {bold $NAME-$VERSION} already exists.}"
          else
            git checkout -b $NAME-$VERSION
          fi

          git add .
          git commit -m "$NAME:$VERSION"
          git push origin $NAME-$VERSION

          npx chalk -t "{green Committed package {bold $NAME} {bold $VERSION}.}"
